title: Home Lab
theme: dark
color: slate

layout:
  Media:
    style: row
    columns: 4
  Productivity:
    style: row
    columns: 4
  Gaming:
    style: row
    columns: 2
  Infrastructure:
    style: row
    columns: 3
  Cerberus:
    style: row
    columns: 3
  Home Assistant:
    style: row
    columns: 1
